[package]
name = "hearth-mud"
version = "0.1.0"
edition = "2024"

[features]
default = []
bundle-web = ["dep:rust-embed"]

[dependencies]
rust-embed = { version = "8", optional = true }
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
argon2 = { version = "0.5", features = ["std"] }
password-hash = { version = "0.5", features = ["getrandom"] }
rusqlite = { version = "0.35", features = ["bundled"] }
mlua = { version = "0.10", features = ["luau", "serialize", "send"] }
axum = { version = "0.8", features = ["ws"] }
tower-http = { version = "0.6", features = ["cors", "fs"] }
futures-util = "0.3"
toml = "0.8"
mapgen = "0.6.0"
rand = "0.8"
noise = "0.9"
bladeink = "2.0.0"
bladeink-compiler = "2.0.0"
